title: Cody Badger
description: Personal website and portfolio
url: "https://codycardbadger.com"
baseurl: ""

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - .bundle/
